"""initial security schema

Revision ID: bc7be07d1985
Revises: 
Create Date: 2026-09-25 19:39:17.698672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7be07d1985'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_hash'), 'documents', ['document_hash'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_table('decryption_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('session_nonce', sa.String(length=128), nullable=False),
    sa.Column('watermark_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_nonce')
    )
    op.create_index(op.f('ix_decryption_sessions_document_id'), 'decryption_sessions', ['document_id'], unique=False)
    op.create_index(op.f('ix_decryption_sessions_recipient_id'), 'decryption_sessions', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_decryption_sessions_watermark_id'), 'decryption_sessions', ['watermark_id'], unique=True)
    op.create_table('provenance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('watermark_id', sa.String(length=128), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=100), nullable=False),
    sa.Column('ledger_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['decryption_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_hash')
    )
    op.create_index(op.f('ix_provenance_records_document_hash'), 'provenance_records', ['document_hash'], unique=False)
    op.create_index(op.f('ix_provenance_records_recipient_id'), 'provenance_records', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_provenance_records_session_id'), 'provenance_records', ['session_id'], unique=True)
    op.create_index(op.f('ix_provenance_records_watermark_id'), 'provenance_records', ['watermark_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provenance_records_watermark_id'), table_name='provenance_records')
    op.drop_index(op.f('ix_provenance_records_session_id'), table_name='provenance_records')
    op.drop_index(op.f('ix_provenance_records_recipient_id'), table_name='provenance_records')
    op.drop_index(op.f('ix_provenance_records_document_hash'), table_name='provenance_records')
    op.drop_table('provenance_records')
    op.drop_index(op.f('ix_decryption_sessions_watermark_id'), table_name='decryption_sessions')
    op.drop_index(op.f('ix_decryption_sessions_recipient_id'), table_name='decryption_sessions')
    op.drop_index(op.f('ix_decryption_sessions_document_id'), table_name='decryption_sessions')
    op.drop_table('decryption_sessions')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
